baseURL = "https://rbroc.github.io"
languageCode = "en-us"
title = "Roberta Rocca"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
publishDir = "public"

[params]
    author = "Roberta Rocca"
    description = "Postdoctoral researcher @ Psychoinformatics Lab, UT Austin"
    githubUsername = "rbroc"
    accent = "#A52A2A"
    showBorder = true
    backgroundColor = "white"
    font = "Montserrat"
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    profilePic = "profile.png"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/cv/cv.pdf" #fix this so it's not relative
    name = "CV"
    weight = 3

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 4


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:rbrrcc@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/rbroc"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/RockBerta/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/roberta-rocca-8299a2123/"
    name = "fab fa-linkedin"
    weight = 4
