baseURL = "https://rbroc.github.io"
languageCode = "en-us"
title = "Roberta Rocca"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
publishDir = "rbroc.github.io"

[params]
    author = "Roberta Rocca"
    description = "Postdoctoral researcher, Psychoinformatics Lab, UT Austin"
    githubUsername = "rbroc"
    accent = "#A52A2A"
    showBorder = true
    backgroundColor = "white"
    font = "Roboto Mono" #
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "cv/cv.pdf"
    name = "CV"
    weight = 3

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 4

[[menu.main]]
    url = "/other/"
    name = "Other"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:rbrrcc@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/rbroc"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/RockBerta/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "www.linkedin.com/in/roberta-rocca-8299a2123"
    name = "linkedin"
    weight = 4
